version: '3'

services:

  site:
    build: site/

    volumes:
      - ./site:/site

    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: postgres
    restart: always

    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "sitedb"
  